version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - /home/fferris/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  web:
    image: devops-test-container
    container_name: devops-test-container
    environment:
      - MONGODB_CONNECTION_STRING=mongodb:/192.168.1.111:27017
    ports:
      - 8000:8000
    restart: unless-stopped
  